general:
  polling_interval: "180s"
  request_timeout: "20s"
  debug: false

telegram:
  apikey: "telegram-bot-key"

twitch:
  client_id: "client-id"
  client_secret: "client-secret"

chats:
  # List of chat IDs to notify (private / group)
  - chatid: 42424242
    streams:
      twitch:
        # List of Twitch usernames to observe
        - username: "dashducks"
      restreamer:
        # List of restreamer streams to observe
        - baseurl: "https://server.restreamer.tld"
          # Channel ID
          id: "124278c-5a03-45ca-8302-c322f1127232"
          # Optional, for a custom page embedding the restreamer stream
          customurl: "https://stream.wrapper.tld"
      broadcastbox:
        # List of restreamer streams to observe
        - baseurl: "https://server.broadcastbox.tld"
          # Stream key
          id: "key"
          # Optional, for a custom page embedding the broadcast-box stream
          customurl: "https://stream.wrapper.tld"