name: Build & test
on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '>=1.20.0'
      - name: Create config.yml from secrets
        run: echo -n "${{ secrets.CONFIG_YML }}" | base64 --decode > config.yml
      - name: Create streams.yml from secrets
        run: echo -n "${{ secrets.STREAMS_YML }}" | base64 --decode > streams.yml
      - name: ls
        run: ls -la
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...